name: Release

on:
  push:
    branches:
      - v2.X

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Build
      run: python3 build_local.py

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: mtb-super-manifest.zip
        path: *.xml
